apiVersion: v1
kind: Secret
metadata:
  name: bankapp-secret
  namespace: default
type: Opaque
data:
  # Секреты в base64
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET: RndOYWhMS1hlckVWTWRtT3hpSnJUZDhFQ29uUGppbUY=
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_BANKAPP_CLIENT_ID: YmFua2FwcA==
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_BANKAPP_CLIENT_SECRET: RndOYWhMS1hlckVWTWRtT3hpSnJUZDhFQ29uUGppbUY=
  SPRING_R2DBC_PASSWORD: MTIzNDU=