apiVersion: v2
name: bankapp
description: Banking application umbrella chart
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: kafka
    version: "26.1.1"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    alias: kafka
    condition: kafka.enabled