spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.notification_service.domain"
        auto.offset.reset: latest
        enable.auto.commit: true
        auto.commit.interval.ms: 1000
  data:
    redis:
      host: localhost
      port: 6379
  session:
    timeout: 30m

  servlet:
    session:
      cookie:
        same-site: none
        secure: true
        domain: .your-domain.com
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/bankapp
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: bankapp
            client-secret: txXtYYzndfecQVWeWcfBVuIZ3nTld56y
            scope: openid,username
          bankapp:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: bankapp
            client-secret: txXtYYzndfecQVWeWcfBVuIZ3nTld56y
            scope: profile
            client-authentication-method: client_secret_post
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/bankapp
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/bankapp
            user-name-attribute: username
oauth2:
  client:
    registration-id: bankapp
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
api:
  gateway:
    url: http://localhost:8080
logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: INFO
kafka:
  topics:
    notificationsRequests: notifications.requests
