apiVersion: v2
name: kafka-infrastructure
description: Apache Kafka cluster deployment
type: application
version: 1.0.0
appVersion: "3.7.0"
dependencies:
  - name: kafka
    version: "23.0.0"
    repository: "https://charts.bitnami.com/bitnami"