apiVersion: v1
clusters:
  - cluster:
      extensions:
        - extension:
            last-update: ...
            provider: minikube.sigs.k8s.io
            version: v1.37.0
          name: cluster_info
      server: https://host.docker.internal:...
      insecure-skip-tls-verify: true
    name: minikube
contexts:
  - context:
      cluster: minikube
      extensions:
        - extension:
            last-update: ...
            provider: minikube.sigs.k8s.io
            version: v1.37.0
          name: context_info
      namespace: default
      user: minikube
    name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
  - name: minikube
    user:
      client-certificate-data: ...
      client-key-data: ...
