apiVersion: v1
clusters:
- cluster:
    certificate-authority: C:\Users\adm\.minikube\ca.crt
    extensions:
    - extension:
        last-update: Wed, 19 Nov 2025 15:46:25 MSK
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: cluster_info
    server: https://host.docker.internal:6443
    insecure-skip-tls-verify: true
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Wed, 19 Nov 2025 15:46:25 MSK
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: C:\Users\adm\.minikube\profiles\minikube\client.crt
    client-key: C:\Users\adm\.minikube\profiles\minikube\client.key
