{{- if .Values.infrastructure.namespaces.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: bankapp-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: bankapp-test
---
apiVersion: v1
kind: Namespace
metadata:
  name: bankapp-prod
  {{- end }}