{{- if .Values.infrastructure.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: bankapp-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  # Секреты в base64
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET: NjlVOTNHckhpZ1d0N0IxM0VOTGp4RnVwU3J3dmxnZEY=
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_BANKAPP_CLIENT_ID: YmFua2FwcA==
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_BANKAPP_CLIENT_SECRET: NjlVOTNHckhpZ1d0N0IxM0VOTGp4RnVwU3J3dmxnZEY=
  SPRING_R2DBC_PASSWORD: {{ .Values.infrastructure.postgres.password | b64enc | quote }}
  {{- end }}