apiVersion: v2
name: bankapp-umbrella
description: Umbrella chart for BankApp microservices
type: application
version: 1.0.0
appVersion: "1.0"
dependencies:
  - name: account-service
    version: "0.1.0"
    repository: "file://../account-service"
    condition: account-service.enabled
  - name: blocker-service
    version: "0.1.0"
    repository: "file://../blocker-service"
    condition: blocker-service.enabled
  - name: cash-service
    version: "0.1.0"
    repository: "file://../cash-service"
    condition: cash-service.enabled
  - name: exchange-service
    version: "0.1.0"
    repository: "file://../exchange-service"
    condition: exchange-service.enabled
  - name: exchangegenerator-service
    version: "0.1.0"
    repository: "file://../ExchangeGenerator-service"
    condition: exchangegenerator-service.enabled
  - name: front-service
    version: "0.1.0"
    repository: "file://../front-service"
    condition: front-service.enabled
  - name: notification-service
    version: "0.1.0"
    repository: "file://../notification-service"
    condition: notification-service.enabled
  - name: transfer-service
    version: "0.1.0"
    repository: "file://../transfer-service"
    condition: transfer-service.enabled