# Глобальные настройки для всех сервисов
global:
  # Настройки окружения (dev, test, prod)
  environment: dev
  # Общие настройки образов
  image:
    repository: ""
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP

services:
  account-service:
    enabled: true
    fullnameOverride: "account-service"
    image:
      repository: "ghcr.io/dyrshluck/account-service"
      tag: "{{ .Values.global.image.tag }}"
    service:
      port: 8081

  blocker-service:
    enabled: true
    fullnameOverride: "blocker-service"
    image:
      repository: "ghcr.io/dyrshluck/account-service"
      tag: "{{ .Values.global.image.tag }}"
    service:
      port: 8086

  cash-service:
    enabled: true
    fullnameOverride: "cash-service"
    image:
      repository: "{{ .Values.global.image.repository }}/cash-service"
      tag: "{{ .Values.global.image.tag }}"
    service:
      port: 8085

  exchange-service:
    enabled: true
    fullnameOverride: "exchange-service"
    image:
      repository: "{{ .Values.global.image.repository }}/exchange-service"
      tag: "{{ .Values.global.image.tag }}"
    service:
      port: 8088

  ExchangeGenerator-service:
    enabled: true
    fullnameOverride: "exchangegenerator-service"
    image:
      repository: "{{ .Values.global.image.repository }}/exchangegenerator-service"
      tag: "{{ .Values.global.image.tag }}"
    service:
      port: 8084
    ingress:
      enabled: false

  front-service:
    enabled: true
    fullnameOverride: "front-service"
    image:
      repository: "{{ .Values.global.image.repository }}/front-service"
      tag: "{{ .Values.global.image.tag }}"
    service:
      port: 8083

  notification-service:
    enabled: true
    fullnameOverride: "notification-service"
    image:
      repository: "{{ .Values.global.image.repository }}/notification-service"
      tag: "{{ .Values.global.image.tag }}"
    service:
      port: 8087

  transfer-service:
    enabled: true
    fullnameOverride: "transfer-service"
    image:
      repository: "{{ .Values.global.image.repository }}/transfer-service"
      tag: "{{ .Values.global.image.tag }}"
    service:
      port: 8089

# Настройки зависимостей
dependencies:
  redis:
    enabled: true
    fullnameOverride: "redis"
  config:
    name: "bankapp-config"
  secret:
    name: "bankapp-secret"