global:
  environment: test
  namespace: bankapp-test
  image:
    tag: "test-latest"

# Можно отключить некоторые сервисы для тестов
services:
  account-service:
    enabled: true
  blocker-service:
    enabled: true
  cash-service:
    enabled: true
  exchange-service:
    enabled: true
  ExchangeGenerator-service:
    enabled: false
  front-service:
    enabled: true
  gateway-service:
    enabled: true
  notification-service:
    enabled: true
  transfer-service:
    enabled: true
infrastructure:
  postgres:
    enabled: true
    password: "12345"
  redis:
    enabled: true
  keycloak:
    enabled: true
  configmap:
    enabled: true
  secret:
    enabled: true
  namespaces:
    enabled: true
  ingress:
    enabled: true
# Тестовые настройки
dependencies:
  redis:
    enabled: true