global:
  environment: dev
  namespace: bankapp-dev
  image:
    repository: "your-registry"  # Замените на ваш registry
    pullPolicy: IfNotPresent
    tag: "dev-latest"

# Включаем все сервисы
services:
  account-service:
    enabled: true
  blocker-service:
    enabled: true
  cash-service:
    enabled: true
  exchange-service:
    enabled: true
  ExchangeGenerator-service:
    enabled: true
  front-service:
    enabled: true
  gateway-service:
    enabled: true
  notification-service:
    enabled: true
  transfer-service:
    enabled: true

# Включаем инфраструктуру
infrastructure:
  postgres:
    enabled: true
    password: "12345"
  redis:
    enabled: true
  keycloak:
    enabled: true
    import:
      enabled: true
  configmap:
    enabled: true
  secret:
    enabled: true
  namespaces:
    enabled: false
  ingress:
    enabled: true